[theme]
base = "light"
primaryColor = "#314db1"
font = "sans serif"

[theme.light]
backgroundColor = "#e9eff4"
secondaryBackgroundColor = "#d7e0e7"
textColor = "#11243a"

[theme.dark]
backgroundColor = "#1f232b"
secondaryBackgroundColor = "#2a2f39"
textColor = "#eef2f7"

[theme.sidebar]
primaryColor = "#315ab1"

[theme.light.sidebar]
backgroundColor = "#c9d6e7"
secondaryBackgroundColor = "#d6e0ef"
textColor = "#11243a"

[theme.dark.sidebar]
backgroundColor = "#181c23"
secondaryBackgroundColor = "#1f232b"
textColor = "#eef2f7"
